//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Dados
{
    using System;
    using System.Collections.Generic;
    
    public partial class Relato
    {
        public int idrelato { get; set; }
        public byte[] imagem { get; set; }
        public int codtipo { get; set; }
        public System.DateTime data { get; set; }
        public string bairro { get; set; }
        public string descricao { get; set; }
        public byte[] imagem2 { get; set; }
        public byte[] imagem3 { get; set; }
    
        public virtual TipodeRelato TipodeRelato { get; set; }
    }
}
