//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Dados
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class Relato
    {
        public int idrelato { get; set; }
        [Display(Name = "Tipo")]
        public int codtipo { get; set; }
        public System.DateTime data { get; set; }
        [StringLength(50, ErrorMessage = "Limite de 50 caracteres")]
        public string bairro { get; set; }
        [StringLength(100,ErrorMessage="Limite de 100 caracteres")]
        public string descricao { get; set; }
        [Display(Name = "Imagem")]
        public byte[] imagem3 { get; set; }
    
        public virtual TipodeRelato TipodeRelato { get; set; }
    }
}
